version: '3.8'

services:
  backend:
    image: clubs_backend:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=clubs
      - DATABASE_USER_PASSWORD=clubs123
    networks:
      - clubs_network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=clubs
      - POSTGRES_PASSWORD=clubs123
      - POSTGRES_DB=clubs
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clubs_network
    deploy:
      placement:
        constraints: 
          - "node.role==manager"
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

networks:
  clubs_network:
    driver: overlay

volumes:
  postgres_data:
    driver: local