name: Backend Tests

on:
  push:
    branches: [ master, main ]
    paths:
      - 'Backend/**'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'Backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./Backend

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache-dependency-path: Backend/go.sum

    - name: Install dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v -race -coverprofile=coverage.out ./...

    - name: Generate coverage report
      run: go tool cover -html=coverage.out -o coverage.html

    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: Backend/coverage.html

    - name: Display coverage percentage
      run: |
        COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}')
        echo "Total test coverage: $COVERAGE"
        echo "## Test Coverage: $COVERAGE" >> $GITHUB_STEP_SUMMARY