name: Build Cloudflare

on: 
  push:
    branches:
      - main

jobs:
  build-cloudflare:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          architecture: x64
      - run: flutter pub get
      - run: flutter build web --release
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'clubs'
          directory: 'build/web'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}