name: Build and push Docker image
on:
  push:
    branches:
      - master
    paths:
      - 'Backend/**'

permissions:
  packages: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache-dependency-path: Backend/go.sum
      - name: Install dependencies
        run: go get .
      - name: Test with the Go CLI
        run: go test ./...

  build-and-push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    needs:
      - run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./Backend
          push: true
          tags: |
            ghcr.io/nlstn/clubs:latest
            ghcr.io/nlstn/clubs:${{ github.sha }}